version: "3"
services:
  mysql:
    build: './mysql/'
    restart: always
    ports:
    - "3307:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: promobit
    volumes:
      - ./mysql/dump.sql:/data/application/init.sql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
  
  php:
    build: './php/'
    volumes:
      - ./public:/var/www/html/
  
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/